// app/backend/databasePostGet.js
//mockup generated by chatGPT
// This module provides functions to interact with a backend database
// for managing user profiles and location data.




import axios from 'axios';
//npm install axios

// 👇 Replace with your deployed backend base URL
// e.g. Firebase Cloud Functions endpoint, Express server, etc.
const BASE_URL = 'https://your-server.com/api';

/**
 * 🧍 POST - Create a new user in your database
 * @param {Object} userData - { uid, email, displayName, ... }
 */
export async function postNewUser(userData) {
  try {
    const response = await axios.post(`${BASE_URL}/users`, userData);
    return response.data;
  } catch (error) {
    console.error('❌ Error posting new user:', error);
    throw error;
  }
}

/**
 * 👥 GET - Retrieve all user profiles
 */
export async function getAllUsers() {
  try {
    const response = await axios.get(`${BASE_URL}/users`);
    return response.data;
  } catch (error) {
    console.error('❌ Error fetching users:', error);
    throw error;
  }
}

/**
 * ✏️ POST - Update an existing user profile
 * @param {string} userId - User's unique ID
 * @param {Object} updates - Fields to update, e.g. { displayName: "John", age: 25 }
 */
export async function updateUserProfile(userId, updates) {
  try {
    const response = await axios.post(`${BASE_URL}/users/${userId}/update`, updates);
    return response.data;
  } catch (error) {
    console.error('❌ Error updating user profile:', error);
    throw error;
  }
}

/**
 * 📍 POST - Add a new location / marker to your database
 * @param {Object} locationData - { latitude, longitude, title, description, createdBy, ... }
 */
export async function postNewLocation(locationData) {
  try {
    const response = await axios.post(`${BASE_URL}/locations`, locationData);
    return response.data;
  } catch (error) {
    console.error('❌ Error posting new location:', error);
    throw error;
  }
}

/**
 * 🗺️ GET - Get details for a specific location
 * @param {string} locationId - The ID or slug for the location
 */
export async function getLocationDetails(locationId) {
  try {
    const response = await axios.get(`${BASE_URL}/locations/${locationId}`);
    return response.data;
  } catch (error) {
    console.error('❌ Error fetching location details:', error);
    throw error;
  }
}

// examples from chatGPT

import { postNewUser } from '../backend/databasePostGet';

await postNewUser({
  uid: user.uid,
  email: user.email,
  displayName: user.displayName,
});

//--

import { getAllUsers } from '../backend/databasePostGet';

const users = await getAllUsers();
console.log(users);


//--

import { updateUserProfile } from '../backend/databasePostGet';

await updateUserProfile(user.uid, {
  displayName: 'New Name',
  bio: 'Updated bio info',
});


//--

import { postNewLocation } from '../backend/databasePostGet';

await postNewLocation({
  latitude: 44.878,
  longitude: -91.929,
  title: 'New Bar',
  description: 'Cool hangout spot!',
  createdBy: user.uid,
});


//--


import { getLocationDetails } from '../backend/databasePostGet';

const details = await getLocationDetails('abc123');
console.log(details);



/*
why not this??

async function sendUsersToDatabase(users) {
  await fetch("https://your-api.com/users/bulk-insert", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ users })
  });
}


*/